import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:firebase_auth/firebase_auth.dart' as firebase_auth;
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:get_it/get_it.dart';
import 'package:http/http.dart' as http;
import 'package:injectable/injectable.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../core/network/network_info.dart';
import '../features/auth/data/datasources/stripe_remote_datasource.dart';
import 'injection_container.config.dart';

final getIt = GetIt.instance;

/// Generated function for dependency injection.
/// This is generated by build_runner from @InjectableInit() annotation.
@InjectableInit()
GetIt init() => getIt.init();

/// Module for registering external dependencies that cannot be annotated with @injectable.
@module
abstract class ExternalDependenciesModule {
  @lazySingleton
  firebase_auth.FirebaseAuth get firebaseAuth => firebase_auth.FirebaseAuth.instance;

  @lazySingleton
  FirebaseFirestore get firebaseFirestore => FirebaseFirestore.instance;

  @lazySingleton
  FirebaseStorage get firebaseStorage => FirebaseStorage.instance;

  @lazySingleton
  Connectivity get connectivity => Connectivity();

  @lazySingleton
  NetworkInfo networkInfo(Connectivity connectivity) => NetworkInfoImpl(connectivity);

  @lazySingleton
  http.Client get httpClient => http.Client();
}

/// Initialize dependency injection.
///
/// This function should be called in main() before runApp().
Future<void> configureDependencies() async {
  // Register SharedPreferences manually since it requires async initialization
  final sharedPreferences = await SharedPreferences.getInstance();
  getIt.registerLazySingleton<SharedPreferences>(() => sharedPreferences);

  // Initialize injectable - this will be generated by build_runner
  // The init() method is an extension method generated in injection_container.config.dart
  init();

  // Manually register StripeRemoteDataSource until build_runner is run
  // TODO: Remove this after running: flutter pub run build_runner build --delete-conflicting-outputs
  if (!getIt.isRegistered<StripeRemoteDataSource>()) {
    getIt.registerLazySingleton<StripeRemoteDataSource>(
      () => StripeRemoteDataSourceImpl(
        getIt<firebase_auth.FirebaseAuth>(),
        getIt<FirebaseFirestore>(),
        getIt<http.Client>(),
      ),
    );
  }
}
