import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:firebase_auth/firebase_auth.dart' as firebase_auth;
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../core/network/network_info.dart';
import 'injection_container.config.dart';

final getIt = GetIt.instance;

/// Generated function for dependency injection.
/// This is generated by build_runner from @InjectableInit() annotation.
@InjectableInit()
GetIt init() => getIt.init();

/// Module for registering external dependencies that cannot be annotated with @injectable.
@module
abstract class ExternalDependenciesModule {
  @lazySingleton
  firebase_auth.FirebaseAuth get firebaseAuth => firebase_auth.FirebaseAuth.instance;

  @lazySingleton
  FirebaseFirestore get firebaseFirestore => FirebaseFirestore.instance;

  @lazySingleton
  FirebaseStorage get firebaseStorage => FirebaseStorage.instance;

  @lazySingleton
  Connectivity get connectivity => Connectivity();

  @lazySingleton
  NetworkInfo networkInfo(Connectivity connectivity) => NetworkInfoImpl(connectivity);
}

/// Initialize dependency injection.
///
/// This function should be called in main() before runApp().
Future<void> configureDependencies() async {
  // Register SharedPreferences manually since it requires async initialization
  final sharedPreferences = await SharedPreferences.getInstance();
  getIt.registerLazySingleton<SharedPreferences>(() => sharedPreferences);

  // Initialize injectable - this will be generated by build_runner
  // The init() method is an extension method generated in injection_container.config.dart
  init();
}
