import 'dart:io';
import '../../../../core/utils/constants.dart';
import '../../domain/entities/event.dart';

/// Data model for passing event creation data between pages.
class EventCreationData {
  final String title;
  final String description;
  final String theme;
  final DateTime startAt;
  final DateTime endAt;
  final String location;
  final String ticketName;
  final double price;
  final int availability;
  final File? coverImage;
  final File? thumbnailImage;

  EventCreationData({
    required this.title,
    required this.description,
    required this.theme,
    required this.startAt,
    required this.endAt,
    required this.location,
    required this.ticketName,
    required this.price,
    required this.availability,
    this.coverImage,
    this.thumbnailImage,
  });

  /// Convert to Event entity for creation.
  Event toEvent({
    required String orgId,
    String? imagePath,
  }) {
    final now = DateTime.now();
    return Event(
      id: '', // Will be generated by Firestore
      orgId: orgId,
      title: title,
      description: description,
      startAt: startAt,
      endAt: endAt,
      location: EventLocation(
        lat: 0.0, // TODO: Get actual coordinates from location
        lng: 0.0,
        address: location,
      ),
      capacity: availability,
      ticketTypes: [
        TicketType(
          id: 'general',
          title: ticketName,
          priceCents: (price * 100).toInt(),
          quantity: availability,
          salesStart: now,
          salesEnd: startAt.subtract(const Duration(days: 1)),
        ),
      ],
      imagePath: imagePath,
      status: AppConstants.eventStatusPending, // Events need admin approval
      createdAt: now,
      updatedAt: null,
    );
  }
}

